---
language: ruby
cache: bundler
before_install:
  - rm Gemfile.lock || true
  - gem install -V bundler
install:
  - travis_retry bundle install --without development
  - bundle list
rvm:
  - 2.3.0
  - 2.4.0
env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.9.0"
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 5.0.0"
  - PUPPET_VERSION="~> 5.1.0"
  - PUPPET_VERSION="~> 5.2.0"
  - PUPPET_VERSION="~> 5.3.0"
  - PUPPET_VERSION="~> 5.4.0"
  - PUPPET_VERSION="~> 5.5.0"
script:  bundle exec rake test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - feniix@gmail.com
    on_failure: change
    on_success: change

matrix:
  exclude:
    - rvm: 2.3.0
      env: PUPPET_VERSION="~> 3.7.0"
    - rvm: 2.3.0
      env: PUPPET_VERSION="~> 3.8.0"
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 3.7.0"
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 3.8.0"
